---
abstract: 'Parse and validate ISBNs'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
  Test::ISBN: 2.0
  Test::More: 0.95
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Business-ISBN
no_index:
  directory:
    - t
    - inc
requires:
  Business::ISBN::Data: 20140910
  URI: 0
resources:
  repository: https://github.com/briandfoy/business--isbn.git
version: 2.08
