--- #YAML:1.0
name:                Business-ISBN
version:             2.03_01
abstract:            Parse and validate ISBNs
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Business::ISBN::Data:          1.15
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
